version: "3.8"

services:
  order-placement-system:
    build:
      context: ../..
      dockerfile: Dockerfile.dev
      target: builder
    container_name: order-placement-system
    working_dir: /go/src/order-placement-system
    volumes:
      - ../..:/go/src/order-placement-system
    command: ["air"]
    restart: always
    env_file:
      - ../../.env
    ports:
      - "8080:8080"
