// Code generated by mockery v2.53.4. DO NOT EDIT.

package handler

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// OrderHandlerInterface is an autogenerated mock type for the OrderHandlerInterface type
type OrderHandlerInterface struct {
	mock.Mock
}

// ProcessOrders provides a mock function with given fields: c
func (_m *OrderHandlerInterface) ProcessOrders(c *gin.Context) {
	_m.Called(c)
}

// NewOrderHandlerInterface creates a new instance of OrderHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderHandlerInterface {
	mock := &OrderHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
